Первая итерация финалки 10 спринта
DmitreeV/java-filmorate pull request #2
Opened 2022-09-20 17:31 UTC by DmitreeV

2022-09-20 17:49 UTC, DmitreeV commented
Николай приветсвую! 
Дополнение к коммиту
Тесты частично не отрабатывают по той же причине, что и не проходили в прошлой финалке
А именно - не создается юзер , следовательно не создаются друзья и тд.
Но через эндпоинты все работает корректно..

2022-09-21 18:44 UTC, NikolaiDem requested changes

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.userService = userService;
userService лучше использовать в filmService-е, чтобы ослабить связь между контроллером и сервисом.

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film saveFilm(@RequestBody Film film) throws ValidationException {
throws ValidationException здесь лишнее, потому что исключение является непроверяемым (унаследовано от RuntimeException). Аналогично для всех непроверяемых исключений.

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.getLikes().add(user.getId());
Добавление лайка и сохранение id юзера лучше сделать в методе класса Film, так как Film является бизнес объектом с логикой. Аналогично при удалении лайка.

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Методы FilmStorage и UserStorage обозначают одну и ту же функциональность. Лучше сделать один дженерик интерфейс. А FilmStorage и UserStorage отнаследовать от него с указанием параметра типа.

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (users.containsKey(id)) {
Для чего пустой if?

2022-09-21 18:44 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.containsKey(id)) {
Для чего пустой if?

2022-09-21 18:44 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +
Тесты в сборке все же нужно починить.

2022-09-26 11:29 UTC, DmitreeV commented
Тесты в сборке все отрабатывают

2022-09-27 11:03 UTC, NikolaiDem requested changes

2022-09-27 11:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public static void validateFilm(Film film) {
Валидация - это обязанность сервиса, хранилище лишь занимается сохранением и чтением данных. Нужно перенести валидацию в сервис.

2022-09-27 11:03 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public static void validateUser(User user){
Валидация - это обязанность сервиса, хранилище лишь занимается сохранением и чтением данных. Нужно перенести валидацию в сервис.

2022-09-28 18:43 UTC, NikolaiDem requested changes

2022-09-28 18:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film != null) {
Если что-то оказалось null, то нужно бросить исключение.
А вообще лучше удалить if-ы, хранилище должно гарантировать, что возвращаются данные. Аналогично для deleteLike(...).
Аналогично для методов addFriend(...) и deleteFriend(...) в UserService(...).

2022-09-28 18:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getReleaseDate() != null && film.getReleaseDate().isBefore(OLD_DATE)) {
if (film.getReleaseDate() == null || film.getReleaseDate().isBefore(OLD_DATE)) {}
потому что дата релиза не может быть null.

2022-09-28 18:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if(user.getLogin().isBlank() || user.getLogin().contains(" ")) {
if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {}

2022-09-28 18:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        validateFilm(film);
Вызывать методы валидации тоже нужно в сервисе перед вызовом методов репозитория. Аналогично для остальных методов.

2022-09-28 18:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        validateUser(user);
Вызывать методы валидации тоже нужно в сервисе перед вызовом методов репозитория. Аналогично для остальных методов.

2022-09-29 12:16 UTC, NikolaiDem approved these changes

2022-09-29 16:40 UTC, merged