Add database
DmitreeV/java-filmorate pull request #4
Opened 2022-10-23 13:51 UTC by DmitreeV

2022-10-23 13:58 UTC, DmitreeV commented
Николай приветствую! направляю на проверку проект 
из примечаний : в постман не отрабатывает один тест (из 101),
решил отправить , знаю что будут замечания, возможно при их исправлении найду причину неисправности этого теста =)

2022-10-23 21:16 UTC, NikolaiDem requested changes

2022-10-23 21:16 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Поле id здесь лишнее, это вспомогательная таблица.

2022-10-23 21:16 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    id INT UNIQUE NOT NULL,
Добавить primary key.

2022-10-24 19:28 UTC, DmitreeV commented
все тесты в сборке работают

2022-10-25 19:28 UTC, NikolaiDem requested changes

2022-10-25 19:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return updatedFilm;
Добавить лайки перед возвратом фильма.

2022-10-25 19:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Добавить логирование во все методы, которые вызываются из контроллера.

2022-10-25 19:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +public class MpaService {
Добавить логирование во все методы, которые вызываются из контроллера.

2022-10-25 19:28 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>  public class UserService {
Добавить логирование во все методы, которые вызываются из контроллера.

2022-10-26 15:46 UTC, DmitreeV commented
Николай добрый вечер, внес необходимые правки по замечаниям, к сожалению в некоторых вопросах не смог разобраться (оставил комментарии под замечанием)
Сборка работает)

2022-10-26 15:48 UTC, DmitreeV commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        final String qs = "SELECT * FROM films AS f " +
при сортировке по rate падает один из тестов
очень долго разбирался, так и не понял почему(

2022-10-27 15:31 UTC, NikolaiDem requested changes

2022-10-27 15:31 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +        String qs = "SELECT u.* FROM friendships f " +
Тест с 3мя пользователями непрезентабелен, сделать тест хотя бы с количеством друзей у каждого пользователя 3~5
В твоем текущем запросе происходит объединение друзей одного и другого пользователей, а нужно искать их пересечение. Попробуй поисследовать, как составить запрос только с помощью джойнов.

2022-10-27 15:31 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS MPA_rating CASCADE ;
Таблицы все еще удаляются.

2022-10-27 15:32 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
И для удаления юзера тоже в UserController-е

2022-10-30 09:27 UTC, NikolaiDem approved these changes

2022-10-30 14:33 UTC, merged